//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Predio { get; set; }
        public string Comuna { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
    }
}
